name: dinov2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pytorch
  - pytorch-cuda=12.1
  - pip:
      - transformers==4.50.3
      - datasets==2.14.5
      - scikit-learn==1.3.0
      - numpy==1.26.3
      - tqdm==4.66.1
      - matplotlib==3.7.3
      - ipykernel==6.29.0